import React, { createContext, useState, useContext, ReactNode } from 'react';

const translations = {
  en: {
    // Landing Page
    landingTitle: 'The Smartest Loyalty Program',
    landingSubtitle: 'Turn every customer into a regular. Effortless digital loyalty cards for your business.',
    landingForBusinesses: 'For Businesses',
    landingForCustomers: 'For Customers',
    landingCtaBusiness: 'Contact Us',
    landingCtaCustomer: 'Get Your Card',
    landingHeroTitle1: 'Loyalty that',
    landingHeroTitle2: 'flows effortlessly.',
    landingHeroSubtitle: 'The universal digital wallet for modern businesses. One QR identity. Endless rewards. Zero friction.',
    landingSolutionsTitle: 'Modern Retention.',
    landingSolutionsSubtitle: 'A new standard for customer engagement',
    landingBentoAutomatedTitle: 'Automated Growth',
    landingBentoAutomatedDesc: 'Systematic rewards that keep users returning without manual effort.',
    landingBentoUniversalTitle: 'Universal Access',
    landingBentoUniversalDesc: 'No apps to download. The entire QRoyal experience lives in any standard mobile browser.',
    landingBentoBrandingTitle: 'Branding Hub',
    landingBentoBrandingDesc: 'Customize your loyalty identity with specific colors, logos, and custom QR designs.',
    landingStatsScan: 'Scan Speed',
    landingStatsUptime: 'Uptime',
    landingStatsSync: 'Points Sync',
    landingStatsDownloads: 'App Downloads',
    landingFinalCtaTitle: 'Upgrade to Royal Grade.',
    landingFinalCtaButton: 'Start Free Pilot',
    landingFinalCtaDemo: 'Request Enterprise Demo',
    landingFinalCtaSub: 'Deployed globally in under 5 minutes.',
    landingFooterTagline: 'Infrastructure for loyalty.',
    landingFooterTechnology: 'Technology',
    landingFooterCompany: 'Company',
    landingFooterSupport: 'Support',
    howItWorks: 'How it Works',
    howStep1: 'Business Creates Program',
    howStep1Desc: 'Sign up, customize your profile, and set your loyalty rules in minutes.',
    howStep2: 'Customer Scans QR',
    howStep2Desc: 'Customers scan a QR in-store or online to get their digital loyalty card.',
    howStep3: 'Points & Rewards',
    howStep3Desc: 'You scan their QR on each visit to award points. The system handles reward tracking automatically.',
    oneProgramAllNeeds: 'One program for all your needs',

    // Customer Features Section
    customerFeaturesTitle: 'Everything You Need, in One Digital Card',
    customerFeaturesSubtitle: 'No apps, no hassle. Just a simple, powerful loyalty card that lives in your browser.',
    customerFeature1Title: 'Your Universal Pass',
    customerFeature1Desc: 'One QR code is all you need. Join any participating business instantly and leave the physical cards at home.',
    customerFeature2Title: 'Track Points & Gifts',
    customerFeature2Desc: 'Watch your points grow in real-time and get notified instantly when you earn a reward. No more guessing!',
    customerFeature3Title: 'Customize Your Style',
    customerFeature3Desc: 'Make your card your own. Choose from unique styles, colors, and logos offered by businesses.',
    customerFeature4Title: 'Discover New Places',
    customerFeature4Desc: 'Find popular and nearby businesses, check out their profiles, and join their loyalty programs with a single tap.',

    // Business Features Section
    businessFeaturesTitle: 'The All-in-One Toolkit for Growth',
    businessFeaturesSubtitle: 'Everything you need to build a thriving loyalty program, understand your customers, and grow your business.',
    businessFeature1Title: 'Instant Analytics',
    businessFeature1Desc: 'Track new members, points awarded, and rewards claimed with a simple, real-time dashboard.',
    businessFeature2Title: 'Engage with Posts',
    businessFeature2Desc: 'Announce new products, share updates, or create special offers directly on your public profile.',
    businessFeature3Title: 'Full Customization',
    businessFeature3Desc: 'Set your own rules for points and rewards. Customize your profile with your logo, colors, and more.',
    businessFeature4Title: 'Simple CRM',
    businessFeature4Desc: 'View your full customer list, see their points, and understand who your most loyal regulars are.',

    // General
    customerSignin: 'Customer Signin',
    scanToLogin: 'Scan to Login',
    businessLogin: 'Business Login',
    welcome: 'Welcome',
    points: 'Points',
    viewDiscounts: 'View Discounts',
    visitFacebook: 'Visit our Facebook',
    installPwa: 'Install App on your Phone',
    customerNotFound: 'Customer not found.',
    errorUnexpected: 'An unexpected error occurred.',
    error: 'Error',
    discounts: 'Discounts',
    back: 'Back',
    noDiscounts: 'No discounts available at the moment.',
    expires: 'Expires',
    giftWon: 'Congratulations!',
    giftWonMessage: 'You have earned a free gift! Show this to the staff to claim your reward.',
    close: 'Close',
    enterPhoneNumber: 'Enter Your Phone Number',
    enterPhoneNumberPrompt: 'Please enter your phone number so we can find you more easily.',
    save: 'Save',
    phoneNumber: 'Phone Number',
    // Business Page
    businessDashboard: 'Business Dashboard',
    totalCustomers: 'Total Customers',
    customerList: 'Customer List',
    searchByName: 'Search by Name, Phone, ID...',
    name: 'Name',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    remove: 'Remove',
    removeConfirm: 'Are you sure you want to remove this customer? This action cannot be undone.',
    scanCustomerQR: 'Scan Customer QR',
    logout: 'Logout',
    createNewCustomer: 'Create New Customer',
    createNewCustomerDesc: 'Generate a QR for a new user.',
    newCustomerQrModalTitle: 'New Customer QR Code',
    newCustomerQrModalDesc: 'Have the customer scan this code with their phone camera.',
    // Analytics
    analytics: 'Analytics',
    newMembers7d: 'New Members (7d)',
    pointsAwarded7d: 'Points Awarded (7d)',
    rewardsClaimed7d: 'Rewards Claimed (7d)',
    manageContent: 'Manage Content & Profile',
    manageContentDesc: 'Edit posts, products, and profile details.',
    // Quick Actions
    createNewPost: 'Create New Post',
    createNewPostDesc: 'Share an update with your customers.',
    // Scanner Page
    scanQRCode: 'Scan QR Code',
    pointScanner: 'Point Scanner',
    scanResult: 'Scan Result',
    scanNext: 'Scan Next',
    // Login Page
    businessAreaLogin: 'Business Area Login',
    password: 'Password',
    login: 'Login',
    email: 'Email',
    invalidCredentials: 'Invalid email or password.',
    // Signup
    customerSignup: 'Create Your Loyalty Card',
    businessSignup: 'Create Business',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signup: 'Sign Up',
    createAccount: 'Create Account',
    getYourQRCode: 'Get Your QR Code',
    yourQRCodeIsReady: 'Your Universal QR Code is Ready!',
    scanThisToLogin: 'Use this QR at any participating business to join their program and earn points.',
    goToMyCard: 'Go to My Card',
    businessName: 'Business Name',
    signupSuccess: 'Signup successful! Please log in.',
    // Editor Page
    businessSettings: 'Business Settings',
    publicProfile: 'Public Profile',
    publicProfileDesc: 'This information is visible to customers.',
    defaultProfileTab: 'Default Profile Tab',
    defaultProfileTabDesc: 'Choose which tab customers see first when they visit your profile.',
    qrCustomization: 'Business QR Customization',
    qrCustomizationDesc: 'Customize your own QR for quick business login.',
    logoUrl: 'Logo Image URL',
    coverPhotoUrl: 'Cover Photo URL',
    publicBusinessName: 'Public Business Name',
    bio: 'Business Bio',
    website: 'Website URL',
    facebook: 'Facebook URL',
    instagram: 'Instagram URL',
    contactPhone: 'Contact Phone',
    qrColor: 'QR Code Color',
    eyeShape: 'Eye Shape (Corners)',
    dotStyle: 'Dot Style (Pixels)',
    saveSettings: 'Save Settings',
    saveSuccess: 'Settings saved successfully!',
    saveError: 'Failed to save settings.',
    loyaltyProgram: 'Loyalty Program',
    loyaltyProgramDesc: 'Define how customers earn points and rewards.',
    pointsPerScan: 'Points Awarded Per Scan',
    rewardThreshold: 'Points Needed for Reward',
    rewardMessage: 'Reward Message',
    rewardMessagePlaceholder: 'e.g., You get a free coffee!',
    customerQrDesigns: 'Customer QR Designs',
    customerQrDesignsDesc: 'Offer unique QR code styles for your customers.',
    addDesign: 'Add Design',
    noDesigns: 'No custom designs created yet.',
    deleteDesign: 'Delete Design',
    businessLocation: 'Business Location',
    address: 'Address',
    searchAddress: 'Search for your address...',
    // Content Management
    posts: 'Posts',
    managePosts: 'Manage Posts',
    managePostsDesc: 'Create and edit announcements for your profile.',
    newPost: 'New Post',
    editPost: 'Edit Post',
    title: 'Title',
    content: 'Content (optional)',
    description: 'Description (optional)',
    imageUrl: 'Image URL (optional)',
    videoUrl: 'Video URL (e.g., YouTube)',
    postType: 'Post Type',
    standardPost: 'Standard Post',
    discountOffer: 'Discount / Offer',
    priceOffer: 'Price / Offer Text',
    externalLink: 'External Link URL',
    createPost: 'Create Post',
    updatePost: 'Update Post',
    noPosts: 'You have not created any posts yet.',
    manageDiscounts: 'Manage Discounts',
    manageDiscountsDesc: 'Create special offers for customers.',
    newDiscount: 'New Discount',
    discountName: 'Discount Name',
    createDiscount: 'Create Discount',
    noManageDiscounts: 'You have not created any discounts yet.',
    // Customer Setup Modal
    customerSetup: 'Activate Your Card',
    customerSetupPrompt: 'Welcome! Please enter your details to get started.',
    // Customer Dashboard
    home: 'Home',
    search: 'Search',
    profile: 'Profile',
    myMemberships: 'My Memberships',
    noMemberships: 'You haven\'t joined any businesses yet. Use the Search tab to find and join one!',
    searchForBusinesses: 'Search for businesses...',
    join: 'Join',
    joined: 'Joined',
    noBusinessesFound: 'No businesses found.',
    yourProfile: 'Your Profile',
    yourUniversalQr: 'Your Universal QR Code',
    updateProfile: 'Update Profile',
    profilePictureUrl: 'Profile Picture URL',
    profilePicture: 'Profile Picture',
    uploadImage: 'Upload Image',
    updateSuccess: 'Profile updated successfully!',
    joinSuccess: 'Successfully joined business!',
    printQr: 'Print QR',
    popular: 'Popular',
    nearby: 'Nearby',
    all: 'All',
    enableLocation: 'Enable Location',
    gettingLocation: 'Getting your location...',
    locationError: 'Could not get location. Please enable it in your browser settings.',
    // Business Profile Page (Customer)
    businessProfile: 'Business Profile',
    about: 'About',
    more: 'More',
    leaveBusiness: 'Leave Business',
    leaveConfirm: 'Are you sure you want to leave this business? Your points will be permanently lost.',
    cancel: 'Cancel',
    leave: 'Leave',
    noBusinessDiscounts: 'This business currently has no active discounts.',
    contactInfo: 'Contact Information',
    location: 'Location',
    availableQrStyles: 'Available QR Styles',
    setAsMyStyle: 'Set as My Style',
    styleSetSuccess: 'Your QR code style has been updated!',
    viewOnSite: 'View on Site',
    learnMore: 'Learn More',
    noBusinessPosts: 'This business hasn\'t posted anything yet.',
    // Account Deletion
    deleteAccount: 'Delete Account',
    deleteAccountConfirmTitle: 'Delete Your Account?',
    deleteAccountWarning: 'This action is permanent and cannot be undone. All your points and memberships will be lost forever.',
    deleteAccountPrompt: 'To confirm, please type your full phone number:',
    deleteAccountError: 'Failed to delete account. Please try again.',
    deleteSuccess: 'Account deleted successfully.',
    // Kiosk Mode
    kioskMode: 'Kiosk Mode',
    kioskModeDesc: 'Open full-screen scanner.',
    exitKiosk: 'Exit Kiosk Mode',
    scanQr: 'Scan QR',
    createQr: 'Create QR',
    hello: 'Hello',
    contactUs: 'Contact Us',
  },
  el: {
    landingTitle: 'Το Εξυπνότερο Πρόγραμμα Πιστότητας',
    landingSubtitle: 'Μετατρέψτε κάθε πελάτη σε τακτικό. Ψηφιακές κάρτες πιστότητας χωρίς κόπο για την επιχείρησή σας.',
    landingForBusinesses: 'Για Επιχειρήσεις',
    landingForCustomers: 'Για Πελάτες',
    landingCtaBusiness: 'Επικοινωνήστε μαζί μας',
    landingCtaCustomer: 'Πάρε την Κάρτα σου',
    landingHeroTitle1: 'Πιστότητα που',
    landingHeroTitle2: 'ρέει χωρίς προσπάθεια.',
    landingHeroSubtitle: 'Το παγκόσμιο ψηφιακό πορτοφόλι για σύγχρονες επιχειρήσεις. Μία ταυτότητα QR. Ατελείωτες ανταμοιβές.',
    landingSolutionsTitle: 'Σύγχρονη Διατήρηση.',
    landingSolutionsSubtitle: 'Ένα νέο πρότυπο για την αφοσίωση των πελατών',
    landingBentoAutomatedTitle: 'Αυτοματοποιημένη Ανάπτυξη',
    landingBentoAutomatedDesc: 'Συστηματικές ανταμοιβές που κρατούν τους χρήστες να επιστρέφουν χωρίς χειροκίνητη προσπάθεια.',
    landingBentoUniversalTitle: 'Παγκόσμια Πρόσβαση',
    landingBentoUniversalDesc: 'Δεν χρειάζονται εφαρμογές. Ολόκληρη η εμπειρία QRoyal ζει σε οποιοδήποτε πρόγραμμα περιήγησης κινητού.',
    landingBentoBrandingTitle: 'Κέντρο Branding',
    landingBentoBrandingDesc: 'Προσαρμόστε την ταυτότητα πιστότητάς σας με συγκεκριμένα χρώματα, λογότυπα και σχέδια QR.',
    landingStatsScan: 'Ταχύτητα Σάρωσης',
    landingStatsUptime: 'Χρόνος Λειτουργίας',
    landingStatsSync: 'Συγχρονισμός Πόντων',
    landingStatsDownloads: 'Λήψεις Εφαρμογών',
    landingFinalCtaTitle: 'Αναβαθμίστε σε Royal Grade.',
    landingFinalCtaButton: 'Ξεκινήστε Δωρεάν Δοκιμή',
    landingFinalCtaDemo: 'Ζητήστε Επίδειξη',
    landingFinalCtaSub: 'Ανάπτυξη παγκοσμίως σε λιγότερο από 5 λεπτά.',
    landingFooterTagline: 'Υποδομή για πιστότητα.',
    landingFooterTechnology: 'Τεχνολογία',
    landingFooterCompany: 'Εταιρεία',
    landingFooterSupport: 'Υποστήριξη',
    howItWorks: 'Πώς Λειτουργεί',
    howStep1: 'Η Επιχείρηση Δημιουργεί Πρόγραμμα',
    howStep1Desc: 'Εγγραφείτε, προσαρμόστε το προφίλ σας και ορίστε τους κανόνες πιστότητας σε λίγα λεπτά.',
    howStep2: 'Ο Πελάτης Σαρώνει το QR',
    howStep2Desc: 'Οι πελάτες σαρώνουν ένα QR στο κατάστημα ή online για να λάβουν την ψηφιακή τους κάρτα.',
    howStep3: 'Πόντοι & Ανταμοιβές',
    howStep3Desc: 'Σαρώνετε το QR τους σε κάθε επίσκεψη για να δώσετε πόντους. Το σύστημα διαχειρίζεται αυτόματα τις ανταμοιβές.',
    oneProgramAllNeeds: 'Ένα πρόγραμμα για όλες τις ανάγκες σας',
    
    // Customer Features Section
    customerFeaturesTitle: 'Ό,τι Χρειάζεσαι, σε Μία Ψηφιακή Κάρτα',
    customerFeaturesSubtitle: 'Χωρίς εφαρμογές, χωρίς ταλαιπωρία. Απλά μια ισχυρή κάρτα πιστότητας που ζει στον browser σου.',
    customerFeature1Title: 'Το Παγκόσμιο Πάσο σου',
    customerFeature1Desc: 'Ένας κωδικός QR είναι το μόνο που χρειάζεσαι. Γίνε μέλος σε οποιαδήποτε συμμετέχουσα επιχείρηση αμέσως.',
    customerFeature2Title: 'Παρακολούθησε Πόντους & Δώρα',
    customerFeature2Desc: 'Δες τους πόντους σου να αυξάνονται και ενημερώσου αμέσως μόλις κερδίσεις μια ανταμοιβή. Όχι άλλες απορίες!',
    customerFeature3Title: 'Προσάρμοσε το Στυλ σου',
    customerFeature3Desc: 'Κάνε την κάρτα σου μοναδική. Διάλεξε από ξεχωριστά στυλ, χρώματα και λογότυπα που προσφέρουν οι επιχειρήσεις.',
    customerFeature4Title: 'Ανακάλυψε Νέα Μέρη',
    customerFeature4Desc: 'Βρες δημοφιλείς και κοντινές επιχειρήσεις, δες τα προφίλ τους και γίνε μέλος με ένα πάτημα.',

    // Business Features Section
    businessFeaturesTitle: 'Το Πλήρες Εργαλείο για Ανάπτυξη',
    businessFeaturesSubtitle: 'Ό,τι χρειάζεστε για να χτίσετε ένα επιτυχημένο πρόγραμμα πιστότητας, να κατανοήσετε τους πελάτες σας και να αναπτύξετε την επιχείρησή σας.',
    businessFeature1Title: 'Άμεσα Αναλυτικά Στοιχεία',
    businessFeature1Desc: 'Παρακολουθήστε νέα μέλη, πόντους που δόθηκαν και ανταμοιβές που διεκδικήθηκαν με έναν απλό πίνακα ελέγχου.',
    businessFeature2Title: 'Επικοινωνία με Αναρτήσεις',
    businessFeature2Desc: 'Ανακοινώστε νέα προϊόντα, μοιραστείτε ενημερώσεις ή δημιουργήστε ειδικές προσφορές απευθείας στο δημόσιο προφίλ σας.',
    businessFeature3Title: 'Πλήρης Προσαρμογή',
    businessFeature3Desc: 'Ορίστε τους δικούς σας κανόνες για πόντους και ανταμοιβές. Προσαρμόστε το προφίλ σας με το λογότυπο, τα χρώματα και άλλα.',
    businessFeature4Title: 'Απλό CRM Πελατών',
    businessFeature4Desc: 'Δείτε την πλήρη λίστα πελατών σας, τους πόντους τους και κατανοήστε ποιοι είναι οι πιο πιστοί σας τακτικοί πελάτες.',

    customerSignin: 'Είσοδος Πελάτη',
    scanToLogin: 'Σάρωση για Είσοδο',
    businessLogin: 'Είσοδος Επιχείρησης',
    welcome: 'Καλώς ήρθες',
    points: 'Πόντοι',
    viewDiscounts: 'Δείτε τις Προσφορές',
    visitFacebook: 'Επισκεφθείτε το Facebook μας',
    installPwa: 'Εγκατάσταση Εφαρμογής',
    customerNotFound: 'Ο πελάτης δεν βρέθηκε.',
    errorUnexpected: 'Παρουσιάστηκε ένα μη αναμενόμενο σφάλμα.',
    error: 'Σφάλμα',
    discounts: 'Προσφορές',
    back: 'Πίσω',
    noDiscounts: 'Δεν υπάρχουν διαθέσιμες προσφορές αυτή τη στιγμή.',
    expires: 'Λήγει',
    giftWon: 'Συγχαρητήρια!',
    giftWonMessage: 'Κερδίσατε ένα δωρεάν δώρο! Δείξτε αυτό στο προσωπικό για να το παραλάβετε.',
    close: 'Κλείσιμο',
    enterPhoneNumber: 'Εισαγάγετε τον αριθμό τηλεφώνου σας',
    enterPhoneNumberPrompt: 'Παρακαλώ εισάγετε τον αριθμό του τηλεφώνου σας για να σας βρίσκουμε πιο εύκολα.',
    save: 'Αποθήκευση',
    phoneNumber: 'Αριθμός Τηλεφώνου',
    businessDashboard: 'Πίνακας Ελέγχου',
    totalCustomers: 'Σύνολο Πελατών',
    customerList: 'Λίστα Πελατών',
    searchByName: 'Αναζήτηση με Όνομα, Τηλ, ID...',
    name: 'Όνομα',
    actions: 'Ενέργειες',
    edit: 'Επεξεργασία',
    delete: 'Διαγραφή',
    remove: 'Αφαίρεση',
    removeConfirm: 'Είστε σίγουροι ότι θέλετε να αφαιρέσετε αυτόν τον πελάτη; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    scanCustomerQR: 'Σάρωση QR Πελάτη',
    logout: 'Αποσύνδεση',
    createNewCustomer: 'Δημιουργία Νέου Πελάτη',
    createNewCustomerDesc: 'Δημιουργία QR για νέο χρήστη.',
    newCustomerQrModalTitle: 'Κωδικός QR Νέου Πελάτη',
    newCustomerQrModalDesc: 'Δώστε στον πελάτη να σκανάρει αυτόν τον κωδικό με την κάμερα του.',
    analytics: 'Αναλυτικά Στοιχεία',
    newMembers7d: 'Νέα Μέλη (7η)',
    pointsAwarded7d: 'Πόντοι (7η)',
    rewardsClaimed7d: 'Ανταμοιβές (7η)',
    manageContent: 'Διαχείριση Περιεχομένου & Προφίλ',
    manageContentDesc: 'Επεξεργασία αναρτήσεων, προϊόντων και προφίλ.',
    createNewPost: 'Δημιουργία Νέας Ανάρτησης',
    createNewPostDesc: 'Μοιραστείτε μια ενημέρωση με τους πελάτες σας.',
    scanQRCode: 'Σάρωση Κωδικού QR',
    pointScanner: 'Σαρωτής Πόντων',
    scanResult: 'Αποτέλεσμα Σάρωσης',
    scanNext: 'Επόμενη Σάρωση',
    businessAreaLogin: 'Είσοδος στην Περιοχή Επιχείρησης',
    password: 'Κωδικός',
    login: 'Είσοδος',
    email: 'Email',
    invalidCredentials: 'Λάθος email ή κωδικός.',
    customerSignup: 'Δημιούργησε την Κάρτα σου',
    businessSignup: 'Δημιουργία Επιχείρησης',
    alreadyHaveAccount: 'Έχετε ήδη λογαριασμό;',
    dontHaveAccount: "Δεν έχετε λογαριασμό;",
    signup: 'Εγγραφή',
    createAccount: 'Δημιουργία Λογαριασμού',
    getYourQRCode: 'Λήψη του QR Κωδικού σας',
    yourQRCodeIsReady: 'Ο Παγκόσμιος QR Κωδικός σας είναι έτοιμος!',
    scanThisToLogin: 'Χρησιμοποιήστε αυτό το QR σε οποιαδήποτε συμμετέχουσα επιχείρηση για να εγγραφείτε και να κερδίσετε πόντους.',
    goToMyCard: 'Πήγαινε στην Κάρτα μου',
    businessName: 'Όνομα Επιχείρησης',
    signupSuccess: 'Η εγγραφή ολοκληρώθηκε! Παρακαλώ συνδεθείτε.',
    businessSettings: 'Ρυθμίσεις Επιχείρησης',
    publicProfile: 'Δημόσιο Προφίλ',
    publicProfileDesc: 'Αυτές οι πληροφορίες είναι ορατές στους πελάτες.',
    defaultProfileTab: 'Προεπιλεγμένη Καρτέλα Προφίλ',
    defaultProfileTabDesc: 'Επιλέξτε ποια καρτέλα βλέπουν πρώτα οι πελάτες.',
    qrCustomization: 'Προσαρμογή QR Επιχείρησης',
    qrCustomizationDesc: 'Προσαρμόστε τον δικό σας κωδικό QR για γρήγορη είσοδο.',
    logoUrl: 'URL Εικόνας Λογοτύπου',
    coverPhotoUrl: 'URL Εικόνας Εξωφύλλου',
    publicBusinessName: 'Δημόσιο Όνομα Επιχείρησης',
    bio: 'Περιγραφή Επιχείρησης',
    website: 'URL Ιστοσελίδας',
    facebook: 'URL Facebook',
    instagram: 'URL Instagram',
    contactPhone: 'Τηλέφωνο Επικοινωνίας',
    qrColor: 'Χρώμα Κωδικού QR',
    eyeShape: 'Σχήμα Γωνιών',
    dotStyle: 'Στυλ Κουκκίδων',
    saveSettings: 'Αποθήκευση Ρυθμίσεων',
    saveSuccess: 'Οι ρυθμίσεις αποθηκεύτηκαν επιτυχώς!',
    saveError: 'Αποτυχία αποθήκευσης των ρυθμίσεων.',
    loyaltyProgram: 'Πρόγραμμα Πιστότητας',
    loyaltyProgramDesc: 'Ορίστε πώς οι πελάτες κερδίζουν πόντους και ανταμοιβές.',
    pointsPerScan: 'Πόντοι ανά Σάρωση',
    rewardThreshold: 'Απαιτούμενοι Πόντοι για Ανταμοιβή',
    rewardMessage: 'Μήνυμα Ανταμοιβής',
    rewardMessagePlaceholder: 'π.χ., Κερδίζετε έναν δωρεάν καφέ!',
    customerQrDesigns: 'Σχέδια QR Πελατών',
    customerQrDesignsDesc: 'Προσφέρετε μοναδικά στυλ QR στους πελάτες σας.',
    addDesign: 'Προσθήκη Σχεδίου',
    noDesigns: 'Δεν έχετε δημιουργήσει προσαρμοσμένα σχέδια.',
    deleteDesign: 'Διαγραφή Σχεδίου',
    businessLocation: 'Τοποθεσία Επιχείρησης',
    address: 'Διεύθυνση',
    searchAddress: 'Αναζήτηση για τη διεύθυνσή σας...',
    posts: 'Αναρτήσεις',
    managePosts: 'Διαχείριση Αναρτήσεων',
    managePostsDesc: 'Δημιουργία και επεξεργασία ανακοινώσεων.',
    newPost: 'Νέα Ανάρτηση',
    editPost: 'Επεξεργασία Ανάρτησης',
    title: 'Τίτλος',
    content: 'Περιεχόμενο (προαιρετικό)',
    description: 'Περιγραφή (προαιρετικό)',
    imageUrl: 'URL Εικόνας (προαιρετικό)',
    videoUrl: 'URL Βίντεο (π.χ. YouTube)',
    postType: 'Τύπος Ανάρτησης',
    standardPost: 'Κανονική Ανάρτηση',
    discountOffer: 'Έκπτωση / Προσφορά',
    priceOffer: 'Τιμή / Κείμενο Προσφοράς',
    externalLink: 'Εξωτερικός Σύνδεσμος URL',
    createPost: 'Δημιουργία Ανάρτησης',
    updatePost: 'Ενημέρωση Ανάρτησης',
    noPosts: 'Δεν έχετε δημιουργήσει αναρτήσεις.',
    manageDiscounts: 'Διαχείριση Εκπτώσεων',
    manageDiscountsDesc: 'Δημιουργήστε ειδικές προσφορές.',
    newDiscount: 'Νέα Έκπτωση',
    discountName: 'Όνομα Έκπτωσης',
    createDiscount: 'Δημιουργία Έκπτωσης',
    noManageDiscounts: 'Δεν έχετε δημιουργήσει εκπτώσεις.',
    customerSetup: 'Ενεργοποίηση Κάρτας',
    customerSetupPrompt: 'Καλώς ήρθες! Παρακαλώ εισάγετε τα στοιχεία σας για να ξεκινήσετε.',
    home: 'Αρχική',
    search: 'Αναζήτηση',
    profile: 'Προφίλ',
    myMemberships: 'Οι Συνδρομές μου',
    noMemberships: 'Δεν έχετε εγγραφεί ακόμα σε καμία επιχείρηση. Χρησιμοποιήστε την Αναζήτηση για να βρείτε μία!',
    searchForBusinesses: 'Αναζήτηση επιχειρήσεων...',
    join: 'Συμμετοχή',
    joined: 'Συμμετέχετε',
    noBusinessesFound: 'Δεν βρέθηκαν επιχειρήσεις.',
    yourProfile: 'Το Προφίλ σας',
    yourUniversalQr: 'Ο Παγκόσμιος QR σας',
    updateProfile: 'Ενημέρωση Προφίλ',
    profilePictureUrl: 'URL Εικόνας Προφίλ',
    profilePicture: 'Εικόνα Προφίλ',
    uploadImage: 'Ανέβασμα Εικόνας',
    updateSuccess: 'Το προφίλ ενημερώθηκε επιτυχώς!',
    joinSuccess: 'Επιτυχής συμμετοχή στην επιχείρηση!',
    printQr: 'Εκτύπωση QR',
    popular: 'Δημοφιλή',
    nearby: 'Κοντινά',
    all: 'Όλα',
    enableLocation: 'Ενεργοποίηση Τοποθεσίας',
    gettingLocation: 'Λήψη τοποθεσίας...',
    locationError: 'Αδυναμία λήψης τοποθεσίας. Ενεργοποιήστε την στις ρυθμίσεις του περιηγητή σας.',
    businessProfile: 'Προφίλ Επιχείρησης',
    about: 'Πληροφορίες',
    more: 'Περισσότερα',
    leaveBusiness: 'Αποχώρηση από Επιχείρηση',
    leaveConfirm: 'Είστε σίγουροι ότι θέλετε να αποχωρήσετε από αυτή την επιχείρηση; Οι πόντοι σας θα χαθούν οριστικά.',
    cancel: 'Άκυρο',
    leave: 'Αποχώρηση',
    noBusinessDiscounts: 'Αυτή η επιχείρηση δεν έχει ενεργές προσφορές αυτή τη στιγμή.',
    contactInfo: 'Στοιχεία Επικοινωνίας',
    location: 'Τοποθεσία',
    availableQrStyles: 'Διαθέσιμα Στυλ QR',
    setAsMyStyle: 'Ορισμός ως Στυλ μου',
    styleSetSuccess: 'Το στυλ του QR σας ενημερώθηκε!',
    viewOnSite: 'Δείτε το στο Site',
    learnMore: 'Μάθετε Περισσότερα',
    noBusinessPosts: 'Αυτή η επιχείρηση δεν έχει κάνει αναρτήσεις.',
    deleteAccount: 'Διαγραφή Λογαριασμού',
    deleteAccountConfirmTitle: 'Διαγραφή του Λογαριασμού σας;',
    deleteAccountWarning: 'Αυτή η ενέργεια είναι μόνιμη και δεν μπορεί να αναιρεθεί. Όλοι οι πόντοι και οι συνδρομές σας θα χαθούν οριστικά.',
    deleteAccountPrompt: 'Για επιβεβαίωση, πληκτρολογήστε τον πλήρη αριθμό τηλεφώνου σας:',
    deleteAccountError: 'Αποτυχία διαγραφής λογαριασμού. Παρακαλώ δοκιμάστε ξανά.',
    deleteSuccess: 'Ο λογαριασμός διαγράφηκε επιτυχώς.',
    // Kiosk Mode
    kioskMode: 'Λειτουργία Kiosk',
    kioskModeDesc: 'Άνοιγμα σαρωτή πλήρους οθόνης.',
    exitKiosk: 'Έξοδος Kiosk',
    scanQr: 'Σάρωση QR',
    createQr: 'Δημιουργία QR',
    hello: 'Γειά σου',
    contactUs: 'Επικοινωνία',
  },
};

type Language = 'en' | 'el';
type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('el');

  const t = (key: keyof Translations): string => {
    return translations[language][key] || translations['en'][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
