import React, { createContext, useState, useContext, ReactNode } from 'react';

const translations = {
  en: {
    customerSignin: 'Customer Signin',
    scanToLogin: 'Scan to Login',
    businessLogin: 'Business Login',
    welcome: 'Welcome',
    points: 'Points',
    viewDiscounts: 'View Discounts',
    visitFacebook: 'Visit our Facebook',
    installPwa: 'Install App on your Phone',
    customerNotFound: 'Customer not found.',
    errorUnexpected: 'An unexpected error occurred.',
    error: 'Error',
    discounts: 'Discounts',
    back: 'Back',
    noDiscounts: 'No discounts available at the moment.',
    expires: 'Expires',
    giftWon: 'Congratulations!',
    giftWonMessage: 'You have earned a free gift! Show this to the staff to claim your reward.',
    close: 'Close',
    enterPhoneNumber: 'Enter Your Phone Number',
    enterPhoneNumberPrompt: 'Please enter your phone number so we can find you more easily.',
    save: 'Save',
    phoneNumber: 'Phone Number',
    // Business Page
    businessDashboard: 'Business Dashboard',
    totalCustomers: 'Total Customers',
    customerList: 'Customer List',
    searchByName: 'Search by name...',
    name: 'Name',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    remove: 'Remove',
    removeConfirm: 'Are you sure you want to remove this customer? This action cannot be undone.',
    scanCustomerQR: 'Scan Customer QR',
    logout: 'Logout',
    createNewCustomer: 'Create New Customer',
    createNewCustomerDesc: 'Generate a QR for a new user.',
    newCustomerQrModalTitle: 'New Customer QR Code',
    newCustomerQrModalDesc: 'Have the customer scan this code with their phone camera.',
    // Scanner Page
    scanQRCode: 'Scan QR Code',
    pointScanner: 'Point Scanner',
    scanResult: 'Scan Result',
    // Login Page
    businessAreaLogin: 'Business Area Login',
    password: 'Password',
    login: 'Login',
    email: 'Email',
    invalidCredentials: 'Invalid email or password.',
    // Signup
    customerSignup: 'Create Your Loyalty Card',
    businessSignup: 'Business Signup',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signup: 'Sign Up',
    createAccount: 'Create Account',
    getYourQRCode: 'Get Your QR Code',
    yourQRCodeIsReady: 'Your Universal QR Code is Ready!',
    scanThisToLogin: 'Use this QR at any participating business to join their program and earn points.',
    goToMyCard: 'Go to My Card',
    businessName: 'Business Name',
    signupSuccess: 'Signup successful! Please log in.',
    // Editor Page
    businessSettings: 'Business Settings',
    publicProfile: 'Public Profile',
    publicProfileDesc: 'This information is visible to customers.',
    qrCustomization: 'Business QR Customization',
    qrCustomizationDesc: 'Customize your own QR for quick business login.',
    logoUrl: 'Logo Image URL',
    publicBusinessName: 'Public Business Name',
    bio: 'Business Bio',
    website: 'Website URL',
    facebook: 'Facebook URL',
    instagram: 'Instagram URL',
    contactPhone: 'Contact Phone',
    qrColor: 'QR Code Color',
    eyeShape: 'Eye Shape (Corners)',
    dotStyle: 'Dot Style (Pixels)',
    saveSettings: 'Save Settings',
    saveSuccess: 'Settings saved successfully!',
    saveError: 'Failed to save settings.',
    loyaltyProgram: 'Loyalty Program',
    loyaltyProgramDesc: 'Define how customers earn points and rewards.',
    pointsPerScan: 'Points Awarded Per Scan',
    rewardThreshold: 'Points Needed for Reward',
    rewardMessage: 'Reward Message',
    rewardMessagePlaceholder: 'e.g., You get a free coffee!',
    customerQrDesigns: 'Customer QR Designs',
    customerQrDesignsDesc: 'Offer unique QR code styles for your customers.',
    addDesign: 'Add Design',
    noDesigns: 'No custom designs created yet.',
    deleteDesign: 'Delete Design',
    businessLocation: 'Business Location',
    address: 'Address',
    searchAddress: 'Search for your address...',
    // Customer Setup Modal
    customerSetup: 'Activate Your Card',
    customerSetupPrompt: 'Welcome! Please enter your details to get started.',
    // Customer Dashboard
    home: 'Home',
    search: 'Search',
    profile: 'Profile',
    myMemberships: 'My Memberships',
    noMemberships: 'You haven\'t joined any businesses yet. Use the Search tab to find and join one!',
    searchForBusinesses: 'Search for businesses...',
    join: 'Join',
    joined: 'Joined',
    noBusinessesFound: 'No businesses found.',
    yourProfile: 'Your Profile',
    yourUniversalQr: 'Your Universal QR Code',
    updateProfile: 'Update Profile',
    updateSuccess: 'Profile updated successfully!',
    joinSuccess: 'Successfully joined business!',
    printQr: 'Print QR',
    // Business Profile Page (Customer)
    businessProfile: 'Business Profile',
    leaveBusiness: 'Leave Business',
    leaveConfirm: 'Are you sure you want to leave this business? Your points will be permanently lost.',
    cancel: 'Cancel',
    leave: 'Leave',
    noBusinessDiscounts: 'This business currently has no active discounts.',
    contactInfo: 'Contact Information',
    location: 'Location',
    availableQrStyles: 'Available QR Styles',
    setAsMyStyle: 'Set as My Style',
    styleSetSuccess: 'Your QR code style has been updated!',
  },
  el: {
    customerSignin: 'Είσοδος Πελάτη',
    scanToLogin: 'Σάρωση για Είσοδο',
    businessLogin: 'Είσοδος Επιχείρησης',
    welcome: 'Καλώς ήρθες',
    points: 'Πόντοι',
    viewDiscounts: 'Δείτε τις Προσφορές',
    visitFacebook: 'Επισκεφθείτε το Facebook μας',
    installPwa: 'Εγκατάσταση Εφαρμογής',
    customerNotFound: 'Ο πελάτης δεν βρέθηκε.',
    errorUnexpected: 'Παρουσιάστηκε ένα μη αναμενόμενο σφάλμα.',
    error: 'Σφάλμα',
    discounts: 'Προσφορές',
    back: 'Πίσω',
    noDiscounts: 'Δεν υπάρχουν διαθέσιμες προσφορές αυτή τη στιγμή.',
    expires: 'Λήγει',
    giftWon: 'Συγχαρητήρια!',
    giftWonMessage: 'Κερδίσατε ένα δωρεάν δώρο! Δείξτε αυτό στο προσωπικό για να το παραλάβετε.',
    close: 'Κλείσιμο',
    enterPhoneNumber: 'Εισαγάγετε τον αριθμό τηλεφώνου σας',
    enterPhoneNumberPrompt: 'Παρακαλώ εισάγετε τον αριθμό του τηλεφώνου σας για να σας βρίσκουμε πιο εύκολα.',
    save: 'Αποθήκευση',
    phoneNumber: 'Αριθμός Τηλεφώνου',
    // Business Page
    businessDashboard: 'Πίνακας Ελέγχου Επιχείρησης',
    totalCustomers: 'Σύνολο Πελατών',
    customerList: 'Λίστα Πελατών',
    searchByName: 'Αναζήτηση με όνομα...',
    name: 'Όνομα',
    actions: 'Ενέργειες',
    edit: 'Επεξεργασία',
    delete: 'Διαγραφή',
    remove: 'Αφαίρεση',
    removeConfirm: 'Είστε σίγουροι ότι θέλετε να αφαιρέσετε αυτόν τον πελάτη; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί.',
    scanCustomerQR: 'Σάρωση QR Πελάτη',
    logout: 'Αποσύνδεση',
    createNewCustomer: 'Δημιουργία Νέου Πελάτη',
    createNewCustomerDesc: 'Δημιουργία QR για νέο χρήστη.',
    newCustomerQrModalTitle: 'Κωδικός QR Νέου Πελάτη',
    newCustomerQrModalDesc: 'Δώστε στον πελάτη να σκανάρει αυτόν τον κωδικό με την κάμερα του.',
    // Scanner Page
    scanQRCode: 'Σάρωση Κωδικού QR',
    pointScanner: 'Σαρωτής Πόντων',
    scanResult: 'Αποτέλεσμα Σάρωσης',
     // Login Page
    businessAreaLogin: 'Είσοδος στην Περιοχή Επιχείρησης',
    password: 'Κωδικός',
    login: 'Είσοδος',
    email: 'Email',
    invalidCredentials: 'Λάθος email ή κωδικός.',
    // Signup
    customerSignup: 'Δημιούργησε την Κάρτα σου',
    businessSignup: 'Εγγραφή Επιχείρησης',
    alreadyHaveAccount: 'Έχετε ήδη λογαριασμό;',
    dontHaveAccount: "Δεν έχετε λογαριασμό;",
    signup: 'Εγγραφή',
    createAccount: 'Δημιουργία Λογαριασμού',
    getYourQRCode: 'Λήψη του QR Κωδικού σας',
    yourQRCodeIsReady: 'Ο Παγκόσμιος QR Κωδικός σας είναι έτοιμος!',
    scanThisToLogin: 'Χρησιμοποιήστε αυτό το QR σε οποιαδήποτε συμμετέχουσα επιχείρηση για να εγγραφείτε και να κερδίσετε πόντους.',
    goToMyCard: 'Πήγαινε στην Κάρτα μου',
    businessName: 'Όνομα Επιχείρησης',
    signupSuccess: 'Η εγγραφή ολοκληρώθηκε! Παρακαλώ συνδεθείτε.',
    // Editor Page
    businessSettings: 'Ρυθμίσεις Επιχείρησης',
    publicProfile: 'Δημόσιο Προφίλ',
    publicProfileDesc: 'Αυτές οι πληροφορίες είναι ορατές στους πελάτες.',
    qrCustomization: 'Προσαρμογή QR Επιχείρησης',
    qrCustomizationDesc: 'Προσαρμόστε τον δικό σας κωδικό QR για γρήγορη είσοδο.',
    logoUrl: 'URL Εικόνας Λογοτύπου',
    publicBusinessName: 'Δημόσιο Όνομα Επιχείρησης',
    bio: 'Περιγραφή Επιχείρησης',
    website: 'URL Ιστοσελίδας',
    facebook: 'URL Facebook',
    instagram: 'URL Instagram',
    contactPhone: 'Τηλέφωνο Επικοινωνίας',
    qrColor: 'Χρώμα Κωδικού QR',
    eyeShape: 'Σχήμα Γωνιών',
    dotStyle: 'Στυλ Κουκκίδων',
    saveSettings: 'Αποθήκευση Ρυθμίσεων',
    saveSuccess: 'Οι ρυθμίσεις αποθηκεύτηκαν επιτυχώς!',
    saveError: 'Αποτυχία αποθήκευσης των ρυθμίσεων.',
    loyaltyProgram: 'Πρόγραμμα Πιστότητας',
    loyaltyProgramDesc: 'Ορίστε πώς οι πελάτες κερδίζουν πόντους και ανταμοιβές.',
    pointsPerScan: 'Πόντοι ανά Σάρωση',
    rewardThreshold: 'Απαιτούμενοι Πόντοι για Ανταμοιβή',
    rewardMessage: 'Μήνυμα Ανταμοιβής',
    rewardMessagePlaceholder: 'π.χ., Κερδίζετε έναν δωρεάν καφέ!',
    customerQrDesigns: 'Σχέδια QR Πελατών',
    customerQrDesignsDesc: 'Προσφέρετε μοναδικά στυλ QR στους πελάτες σας.',
    addDesign: 'Προσθήκη Σχεδίου',
    noDesigns: 'Δεν έχετε δημιουργήσει προσαρμοσμένα σχέδια.',
    deleteDesign: 'Διαγραφή Σχεδίου',
    businessLocation: 'Τοποθεσία Επιχείρησης',
    address: 'Διεύθυνση',
    searchAddress: 'Αναζήτηση για τη διεύθυνσή σας...',
    // Customer Setup Modal
    customerSetup: 'Ενεργοποίηση Κάρτας',
    customerSetupPrompt: 'Καλώς ήρθες! Παρακαλώ εισάγετε τα στοιχεία σας για να ξεκινήσετε.',
    // Customer Dashboard
    home: 'Αρχική',
    search: 'Αναζήτηση',
    profile: 'Προφίλ',
    myMemberships: 'Οι Συνδρομές μου',
    noMemberships: 'Δεν έχετε εγγραφεί ακόμα σε καμία επιχείρηση. Χρησιμοποιήστε την Αναζήτηση για να βρείτε μία!',
    searchForBusinesses: 'Αναζήτηση επιχειρήσεων...',
    join: 'Συμμετοχή',
    joined: 'Συμμετέχετε',
    noBusinessesFound: 'Δεν βρέθηκαν επιχειρήσεις.',
    yourProfile: 'Το Προφίλ σας',
    yourUniversalQr: 'Ο Παγκόσμιος QR σας',
    updateProfile: 'Ενημέρωση Προφίλ',
    updateSuccess: 'Το προφίλ ενημερώθηκε επιτυχώς!',
    joinSuccess: 'Επιτυχής συμμετοχή στην επιχείρηση!',
    printQr: 'Εκτύπωση QR',
    // Business Profile Page (Customer)
    businessProfile: 'Προφίλ Επιχείρησης',
    leaveBusiness: 'Αποχώρηση από Επιχείρηση',
    leaveConfirm: 'Είστε σίγουροι ότι θέλετε να αποχωρήσετε από αυτή την επιχείρηση; Οι πόντοι σας θα χαθούν οριστικά.',
    cancel: 'Άκυρο',
    leave: 'Αποχώρηση',
    noBusinessDiscounts: 'Αυτή η επιχείρηση δεν έχει ενεργές προσφορές αυτή τη στιγμή.',
    contactInfo: 'Στοιχεία Επικοινωνίας',
    location: 'Τοποθεσία',
    availableQrStyles: 'Διαθέσιμα Στυλ QR',
    setAsMyStyle: 'Ορισμός ως Στυλ μου',
    styleSetSuccess: 'Το στυλ του QR σας ενημερώθηκε!',
  },
};

type Language = 'en' | 'el';
type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof Translations) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('el');

  const t = (key: keyof Translations): string => {
    return translations[language][key] || translations['en'][key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};